services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sisorg
      MYSQL_USER: sisorg
      MYSQL_PASSWORD: sisorg
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "server=db;port=3306;database=sisorg;user=sisorg;password=sisorg;TreatTinyAsBoolean=false"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5196:8080"
